### PR TITLE
Fix data entry and dashboards links

### LINKED ISSUE #134: Fix Data Entry and Dashboard links to point to the right sections in the app
We need to discuss this @matiasgarcia91

### PR DESCRIPTION
**Pull request by adrianq**
### :pushpin: References

* **Issue:** Closes #134

### :memo: Implementation
- Data entry and dashboards pages now work even without a dataset id
- Fix links in landing page to point to internal pages

### :fire: Is there anything the reviewer should know to test it?
This will not work in a development environment because of the JS policies for iframes. Either create a virtual link between your local DHIS2 and the build folder or just deploy the app on a DHIS2 server

### :bookmark_tabs: Others

- Any change in the [metadata repo](https://github.com/EyeSeeTea/vaccination-metadata)? If so, what branch/PR?
- Any change in the [GUI library](https://github.com/EyeSeeTea/d2-ui-components)? If so, what branch/PR?

### CODE REVIEW

File: src/components/dashboard/Dashboard.jsx [hunk 1]
```diff
@@ -42,29 +52,39 @@ class Dashboard extends React.Component {
...
         await this.waitforDashboardToLoad(iframeDocument);
         const iFrameRoot = iframeDocument.querySelector("#root");
-        iFrameRoot.style.marginTop = "-110px";
+
         const iFrameWrapper = iframeDocument.querySelector(".app-wrapper");
         iFrameWrapper.removeChild(iFrameWrapper.firstChild).remove();
-        iFrameWrapper.removeChild(iFrameWrapper.firstChild).remove();
+        if (dataSetId) {
+            iFrameRoot.style.marginTop = "-110px";
+            iFrameWrapper.removeChild(iFrameWrapper.firstChild).remove();
```
Comment (tokland) [inline src/components/dashboard/Dashboard.jsx]: There is a problem with the action [Edit], React fails to finds the bar with the dashboards, which it uses to show on edit mode the save/cancel changes: `Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node`.

I tried to hide instead the bar instead of removing it, but then the edit-mode actions are hidden are the user cannot exit the edit.

Maybe the easiest solution is to remove the edit button.

File: src/components/app/LandingPage.js [hunk 2]
```diff
@@ -60,10 +60,10 @@ class LandingPage extends React.Component {
                 history.push("/" + key);
                 break;
             case "data-entry":
-                goToDhis2Url("/dhis-web-dataentry/index.action");
```
Comment (tokland) [inline src/components/app/LandingPage.js]: I've refactored goToDhis2Url (see fc5adcd2), it's better to simply get the baseUrl from the d2 object. This also fixes those urls for a namespaces DHIS2 url (/2.30/...), which was not working.

**Comment by tokland** [comment]
Ready for testing.

Removed edit button and refactored setDashboardStyling. Note that the number of rows of the dashboard list bar is variable and stored (POST api/29/userDataStore/dashboard/controlBarRows), so the height to remove could not be hardcoded. Tested with ID, without ID and different # of rows visibles

**Comment by adrianq** [comment]
@tokland Hiding the edit button was not working for me. The dom element couldn't be found. I guess to load the iframe in my laptop took longer than in yours. I fix it here https://github.com/EyeSeeTea/vaccination-app/pull/142/commits/f2546c9e6038aa5707f2f7245cd46ba2baf61cc4 by waiting for the title bar to load. I am merging this as I don't want to delay the PR anymore but if you can give it a try it would be great!

**Comment by tokland** [comment]
Tested, works well.
